## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(columns = ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Look at NAME counts for binning
count = application_df['NAME'].value_counts()
count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [4]:
# Choose a cutoff value and create a list of application types to be replaced
names_replace = list(count[count<5].index)
# Replace in dataframe
for name in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: NAME, Length: 403, dtype: int64

In [5]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

NAME 403
APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [6]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
counts2 = application_df['CLASSIFICATION'].value_counts()
counts2

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count = counts2[counts2>1]
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (counts2[counts2<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Columns: 447 entries, STATUS to SPECIAL_CONSIDERATIONS_Y
dtypes: float64(444), int64(3)
memory usage: 117.0 MB

In [12]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
node1=80
node2=30
node4=1

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=node1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=node2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=node4, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                35760

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 38221 (149.30 KB)
Trainable params: 38221 (149.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 3ms/step - loss: 0.4748 - accuracy: 0.7743 - val_loss: 0.4274 - val_accuracy: 0.8018
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4305 - accuracy: 0.7946 - val_loss: 0.4310 - val_accuracy: 0.7971
Epoch 3/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4257 - accuracy: 0.7968 - val_loss: 0.4295 - val_accuracy: 0.7984
Epoch 4/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4231 - accuracy: 0.7975 - val_loss: 0.4284 - val_accuracy: 0.7999
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4205 - accuracy: 0.7983 - val_loss: 0.4332 - val_accuracy: 0.8025
Epoch 6/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4194 - accuracy: 0.7987 - val_loss: 0.4318 - val_accuracy: 0.8007
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4179 - accuracy: 0.7992 - val_loss: 0.4336 - val_accuracy: 0.8054
Epoch 8/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4174 - accuracy: 0.8011 - val_loss: 0.4336 - val_accuracy: 0.8031
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4162 - accuracy: 0.8004 - val_loss: 0.4339 - val_accuracy: 0.8005
Epoch 10/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4155 - accuracy: 0.8008 - val_loss: 0.4351 - val_accuracy: 0.8038
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4145 - accuracy: 0.8021 - val_loss: 0.4350 - val_accuracy: 0.8033
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4139 - accuracy: 0.8022 - val_loss: 0.4386 - val_accuracy: 0.8031
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4135 - accuracy: 0.8022 - val_loss: 0.4351 - val_accuracy: 0.8020
Epoch 14/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4125 - accuracy: 0.8023 - val_loss: 0.4378 - val_accuracy: 0.8028
Epoch 15/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8020 - val_loss: 0.4393 - val_accuracy: 0.7974
Epoch 16/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4115 - accuracy: 0.8039 - val_loss: 0.4373 - val_accuracy: 0.8018
Epoch 17/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4112 - accuracy: 0.8043 - val_loss: 0.4363 - val_accuracy: 0.8025
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4110 - accuracy: 0.8043 - val_loss: 0.4393 - val_accuracy: 0.8038
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4105 - accuracy: 0.8046 - val_loss: 0.4394 - val_accuracy: 0.8012
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4096 - accuracy: 0.8053 - val_loss: 0.4390 - val_accuracy: 0.8033
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4095 - accuracy: 0.8058 - val_loss: 0.4391 - val_accuracy: 0.8067
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4089 - accuracy: 0.8054 - val_loss: 0.4391 - val_accuracy: 0.8046
Epoch 23/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4080 - accuracy: 0.8050 - val_loss: 0.4420 - val_accuracy: 0.8044
Epoch 24/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4080 - accuracy: 0.8057 - val_loss: 0.4462 - val_accuracy: 0.8023
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8055 - val_loss: 0.4482 - val_accuracy: 0.8012
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4077 - accuracy: 0.8064 - val_loss: 0.4446 - val_accuracy: 0.8023
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4075 - accuracy: 0.8054 - val_loss: 0.4387 - val_accuracy: 0.8025
Epoch 28/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4066 - accuracy: 0.8065 - val_loss: 0.4439 - val_accuracy: 0.8005
Epoch 29/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4063 - accuracy: 0.8071 - val_loss: 0.4437 - val_accuracy: 0.8023
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4063 - accuracy: 0.8059 - val_loss: 0.4499 - val_accuracy: 0.8028
Epoch 31/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8072 - val_loss: 0.4462 - val_accuracy: 0.8028
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4054 - accuracy: 0.8066 - val_loss: 0.4461 - val_accuracy: 0.8044
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8072 - val_loss: 0.4447 - val_accuracy: 0.8007
Epoch 34/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4052 - accuracy: 0.8068 - val_loss: 0.4428 - val_accuracy: 0.8033
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8071 - val_loss: 0.4443 - val_accuracy: 0.8046
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4050 - accuracy: 0.8069 - val_loss: 0.4508 - val_accuracy: 0.7999
Epoch 37/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8078 - val_loss: 0.4484 - val_accuracy: 0.8015
Epoch 38/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8076 - val_loss: 0.4486 - val_accuracy: 0.8010
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4035 - accuracy: 0.8078 - val_loss: 0.4502 - val_accuracy: 0.8015
Epoch 40/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4039 - accuracy: 0.8077 - val_loss: 0.4470 - val_accuracy: 0.8028
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8067 - val_loss: 0.4488 - val_accuracy: 0.8025
Epoch 42/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8083 - val_loss: 0.4506 - val_accuracy: 0.8025
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8080 - val_loss: 0.4503 - val_accuracy: 0.8023
Epoch 44/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4023 - accuracy: 0.8080 - val_loss: 0.4473 - val_accuracy: 0.8038
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4026 - accuracy: 0.8082 - val_loss: 0.4520 - val_accuracy: 0.8028
Epoch 46/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4024 - accuracy: 0.8086 - val_loss: 0.4536 - val_accuracy: 0.8028
Epoch 47/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4019 - accuracy: 0.8083 - val_loss: 0.4496 - val_accuracy: 0.8023
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4018 - accuracy: 0.8082 - val_loss: 0.4504 - val_accuracy: 0.7999
Epoch 49/100
628/684 [==========================>...] - ETA: 0s - loss: 0.4027 - accuracy: 0.8074

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
from google.colab import files
filename = '/content/AlphabetSoupCharity_Optimization.h5'

nn.save(filename)
files.download(filename)